import type { Metadata } from "next";
import { Inter, Bebas_Neue } from "next/font/google";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";
import CustomThemeProvider from "@/utils/providers/ThemeProvider";
import ReactToastProvider from "@/utils/providers/ReactToastProvider";
import localFont from 'next/font/local'
const myFont = localFont({ src: '../public/fonts/BebasNeue-Regular.ttf' });
import "@/styles/index.scss";

// const inter = Inter({ subsets: ["latin"] });
// const bebas = Inter({ subsets: ["latin"] });
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
 
const bebas = Bebas_Neue({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-bebas-neue',
})
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${bebas.className}`}>
        <ReactQueryProvider>
          <CustomThemeProvider>
            {children}
            </CustomThemeProvider>
          <ReactToastProvider />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
